<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="8" total="18" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="PageObject suite" duration-ms="11917" started-at="2018-02-02T12:05:37Z" finished-at="2018-02-02T12:05:49Z">
    <groups>
    </groups>
    <test name="RMT test" duration-ms="11917" started-at="2018-02-02T12:05:37Z" finished-at="2018-02-02T12:05:49Z">
      <class name="com.zabi.stand_tests.LoginPageTests">
        <test-method status="PASS" signature="startSetup()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="startSetup" is-config="true" duration-ms="5147" started-at="2018-02-02T14:05:37Z" finished-at="2018-02-02T14:05:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSetup -->
        <test-method status="PASS" signature="ButtonResetTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="ButtonResetTest" duration-ms="377" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ButtonResetTest -->
        <test-method status="FAIL" signature="EmptyPasswordTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="EmptyPasswordTest" duration-ms="172" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://86.57.161.116:10008/#login] but found [http://86.57.161.116:10008/#/vacation]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://86.57.161.116:10008/#login] but found [http://86.57.161.116:10008/#/vacation]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.zabi.stand_tests.LoginPageTests.EmptyPasswordTest(LoginPageTests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyPasswordTest -->
        <test-method status="FAIL" signature="IncorrectLoginWithSpacesTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="IncorrectLoginWithSpacesTest" duration-ms="13" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.IncorrectLoginWithSpacesTest(LoginPageTests.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectLoginWithSpacesTest -->
        <test-method status="FAIL" signature="IncorrectLoginWithSymbolsTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="IncorrectLoginWithSymbolsTest" duration-ms="8" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.IncorrectLoginWithSymbolsTest(LoginPageTests.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectLoginWithSymbolsTest -->
        <test-method status="FAIL" signature="LoginIncorrectPasswordTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="LoginIncorrectPasswordTest" duration-ms="9" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.LoginIncorrectPasswordTest(LoginPageTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginIncorrectPasswordTest -->
        <test-method status="FAIL" signature="LoginIncorrectTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="LoginIncorrectTest" duration-ms="12" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.LoginIncorrectTest(LoginPageTests.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginIncorrectTest -->
        <test-method status="FAIL" signature="LoginValidTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="LoginValidTest" duration-ms="9" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.LoginValidTest(LoginPageTests.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValidTest -->
        <test-method status="FAIL" signature="LoginValidTestWithCheckBox()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="LoginValidTestWithCheckBox" duration-ms="90" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.LoginValidTestWithCheckBox(LoginPageTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValidTestWithCheckBox -->
        <test-method status="FAIL" signature="LoginWithClearForm()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="LoginWithClearForm" duration-ms="14" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.LoginPageTests.LoginWithClearForm(LoginPageTests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 26 more
Caused by: java.lang.IllegalStateException: This is not login page!
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:26)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithClearForm -->
        <test-method status="PASS" signature="stopTest()[pri:0, instance:com.zabi.stand_tests.LoginPageTests@10bdf5e5]" name="stopTest" is-config="true" duration-ms="930" started-at="2018-02-02T14:05:43Z" finished-at="2018-02-02T14:05:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopTest -->
      </class> <!-- com.zabi.stand_tests.LoginPageTests -->
      <class name="com.zabi.stand_tests.UserCredsTests">
        <test-method status="FAIL" signature="startSetup()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="startSetup" is-config="true" duration-ms="0" started-at="2018-02-02T14:05:44Z" finished-at="2018-02-02T14:05:44Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:138)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at com.zabi.stand_tests.pageobjects.ProfilePage.getUserMenu(ProfilePage.java:42)
	at com.zabi.stand_tests.UserCredsTests.startSetup(UserCredsTests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:129)
	... 27 more
Caused by: java.lang.NullPointerException
	at com.zabi.stand_tests.pageobjects.LoginPage.<init>(LoginPage.java:24)
	... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSetup -->
        <test-method status="SKIP" signature="commentCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="commentCheck" duration-ms="2" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commentCheck -->
        <test-method status="SKIP" signature="emailCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="emailCheck" duration-ms="2" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailCheck -->
        <test-method status="SKIP" signature="locationCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="locationCheck" duration-ms="5" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- locationCheck -->
        <test-method status="SKIP" signature="nameCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="nameCheck" duration-ms="1" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nameCheck -->
        <test-method status="SKIP" signature="officceCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="officceCheck" duration-ms="1" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- officceCheck -->
        <test-method status="SKIP" signature="phoneNumberCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="phoneNumberCheck" duration-ms="1" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneNumberCheck -->
        <test-method status="SKIP" signature="skypeCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="skypeCheck" duration-ms="1" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skypeCheck -->
        <test-method status="SKIP" signature="specializationCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="specializationCheck" duration-ms="0" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- specializationCheck -->
        <test-method status="SKIP" signature="workstationCheck()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="workstationCheck" duration-ms="8" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- workstationCheck -->
        <test-method status="SKIP" signature="stopTest()[pri:0, instance:com.zabi.stand_tests.UserCredsTests@4b952a2d]" name="stopTest" is-config="true" duration-ms="0" started-at="2018-02-02T14:05:49Z" finished-at="2018-02-02T14:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopTest -->
      </class> <!-- com.zabi.stand_tests.UserCredsTests -->
    </test> <!-- RMT test -->
  </suite> <!-- PageObject suite -->
</testng-results>
